export const ELEMENTS = {
  addAppointmentButton: 'Add Appointment',
  addPeopleButton: 'Add People',
  addPersonCheckbox: 'input[type="checkbox"]',
  addButton: 'button[class="secondary undefined"]',
  appointmentTypeCheckbox: '[formcontrolname="appointmentType"]',
  optionAppointmentType: '[class="ng-option"]',
  addVideoLinkButton: 'button[class="primary undefined"]',
  dataPikerField: '.datetimepicker > [dir="ltr"] > .dp-input-container > .dp-picker-input',
  dateField: '[class="dp-input-container"] > input',
  startHourField: '[formcontrolname="start"]',
  endHourField: '[formcontrolname="end"]',
  hourField: '.dp-time-select-control-hours > .dp-time-select-control-up',
  hourValueField: '.dp-time-select-display-hours',
  meridiumField: '.dp-time-select-control-meridiem > .dp-time-select-control-up',
  meridiumValueField: '.dp-time-select-display-meridiem',
  priceField: '[formcontrolname="price"]',
  statusCheckbox: '[class="ng-select-container ng-has-value"]',
  optionStatus: '[class="ng-option"]',
  saveButton: 'button[class="primary undefined"]',
  tableField: '[class="appointment-table-td"]',
};
