export const ELEMENTS = {
  addAppointmentButton: 'Add Appointment',
  addPeopleButton: 'Add People',
  addPersonCheckbox: 'input[type="checkbox"]',
  addButton: 'button[class="secondary undefined"]',
  appointmentTypeCheckbox: '[formcontrolname="appointmentType"]',
  optionAppointmentType: '[class="ng-option"]',
  addVideoLinkButton: 'button[class="primary undefined"]',
  dateField: '[class="dp-input-container"] > input',
  priceField: '[formcontrolname="price"]',
  statusCheckbox: '[class="ng-select-container ng-has-value"]',
  optionStatus: '[class="ng-option"]',
  saveButton: 'button[class="primary undefined"]',
  tableField: '[class="appointment-table-td"]',
};
